webapp/news/models.py
from webapp.db import db


class News(db.Model):
    __table_args__ = {'extend_existing': True}
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String, nullable=False)
    url = db.Column(db.String, unique=True, nullable=False)
    published = db.Column(db.DateTime, nullable=False)
    text = db.Column(db.Text, nullable=True)

    def __repr__(self):
        return f'<News {self.title} {self.url}'

webapp/user/models.py
from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash

from webapp.db import db


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), index=True, unique=True)  # noqa: WPS432
    password = db.Column(db.String(128))  # noqa: WPS432
    role = db.Column(db.String(10), index=True)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    @property
    def is_admin(self):

        return self.role == 'admin'

    def __repr__(self) -> str:
        return '<User {0}>'.format(self.username)

webapp/user/forms.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    username = StringField(
        'Username',
        validators=[DataRequired()],
        render_kw={'class': 'form-control'},
    )
    password = PasswordField(
        'Password',
        validators=[DataRequired()],
        render_kw={'class': 'form-control'},
    )
    remember_me = BooleanField(
        'Remember me',
        default=True,
        render_kw={'class': 'form-check-imput'},
    )
    submit = SubmitField('Submit', render_kw={'class': 'btn btn-primary'})

webapp/__init__.py
from flask import Flask
from flask_login import LoginManager

from webapp.admin.views import blueprint as admin_blueprint
from webapp.db import db
from webapp.news.views import blueprint as news_blueprint
from webapp.user.models import User
from webapp.user.views import blueprint as user_blueprint


def create_app():
    app = Flask(__name__)
    app.config.from_pyfile('config.py')
    db.init_app(app)

    with app.app_context():
        db.create_all()

    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_view = 'user.login'

    app.register_blueprint(user_blueprint)
    app.register_blueprint(admin_blueprint)
    app.register_blueprint(news_blueprint)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)

    return app

webapp/admin/views.py
from flask import Blueprint, render_template

from webapp.user.decorators import admin_required

blueprint = Blueprint('admin', __name__, url_prefix='/admin')


@blueprint.route('/')
@admin_required
def admin_index():
    title = 'Control panel'
    return render_template('admin/index.html', page_title=title)

webapp/news/views.py
from flask import Blueprint, current_app, render_template

from webapp.news.models import News
from webapp.weather import weather_by_city

blueprint = Blueprint('news', __name__)


@blueprint.route('/')
def index():
    title = 'Новости Python'
    city = current_app.config['WEATHER_DEFAULY_CITY']
    weather = weather_by_city(city)
    news_list = News.query.order_by(News.published.desc()).all()
    return render_template(
        'news/index.html',
        page_title=title,
        weather=weather,
        news_list=news_list,
    )

webapp/user/views.py
from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import current_user, login_user, logout_user

from webapp.user.forms import LoginForm
from webapp.user.models import User

blueprint = Blueprint('user', __name__, url_prefix='/users')


@blueprint.route('/login')
def login():
    if current_user.is_authenticated:
        return redirect(url_for('news.index'))
    title = 'User Login'
    login_form = LoginForm()
    return render_template('user/login.html', page_title=title, form=login_form)


@blueprint.route('/process-login', methods=['POST'])
def process_login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            flash('Success')
            return redirect(url_for('news.index'))
    flash('Wrong username or password')
    return redirect(url_for('user.login'))


@blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('news.index'))

webapp/templates/base.html
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ page_title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>
    {% include 'menu.html' %}
    <div class="container">
    <h1>{{ page_title }}</h1>
        {% block content %}{% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/login.html
<!doctype html>
<html lang="ru">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ page_title }}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
  </head>
  <body>
    <div class="container">
    <h1>{{ page_title }}</h1>
    <div class="row">
        <div class="col-4">
            {% with messages = get_flashed_messages() %}
              {% if messages %}
              <div class="alert alert-warning" role="alert">
                  {% for message in messages %}
                      {{ message }}<br>
                  {% endfor %}
              </div>
              {% endif %}
            {% endwith %}
            <form action="{{ url_for('process_login') }}" method="POST">
                {{  form.hidden_tag() }}
                <div class="form-group">
                    {{ form.username.label }}
                    {{ form.username() }}
                </div>
                <div class="form-group">
                    {{ form.password.label }}
                    {{ form.password() }}
                </div>
                <div class="form-group form-check">
                  {{ form.remember_me() }}
                  {{ form.remember_me.label(class_='form-check-label') }}
                </div>
                    <br>
                    {{ form.submit() }}                    
            </form>
        </div>
        <div class="col-8">
        </div>
    </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

webapp/templates/menu.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Python News</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user.login') }}">Login</a>
          </li>
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>

webapp/templates/news/index.html
{% extends 'base.html' %}
{% block content %}
  <div class="row">
      <div class="col-8">
        {% with messages = get_flashed_messages() %}
          {% if messages %}
          <div class="alert alert-warning" role="alert">
              {% for message in messages %}
                  {{ message }}<br>
              {% endfor %}
          </div>
          {% endif %}
        {% endwith %}

        <h2>Новости</h2>
        {% for news in news_list %}
            <h4><a href="{{ news.url }}">{{ news.title }}</a></h4>
            <p>{{ news.published.strftime('%d.%m.%Y') }}</p>
            <hr />
        {% endfor %}
      </div>
      <div class="col-4">
          <h2>Прогноз погоды</h2>
          {% if weather %}
              Погода: {{ weather.temp_C }}, ощущается как {{ weather.FeelsLikeC }}
          {% else %}
              Сервер погоды временно недоступен
          {% endif %}
      </div>
  </div>
{% endblock %}

webapp/templates/user/login.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="col-4">
            {% with messages = get_flashed_messages() %}
              {% if messages %}
              <div class="alert alert-warning" role="alert">
                  {% for message in messages %}
                      {{ message }}<br>
                  {% endfor %}
              </div>
              {% endif %}
            {% endwith %}
            <form action="{{ url_for('user.process_login') }}" method="POST">
                {{  form.hidden_tag() }}
                <div class="form-group">
                    {{ form.username.label }}
                    {{ form.username() }}
                </div>
                <div class="form-group">
                    {{ form.password.label }}
                    {{ form.password() }}
                </div>
                <div class="form-group form-check">
                  {{ form.remember_me() }}
                  {{ form.remember_me.label(class_='form-check-label') }}
                </div>
                    <br>
                    {{ form.submit() }}                    
            </form>
        </div>
        <div class="col-8">
        </div>
    </div>
{% endblock %}    